# Generated by Django 5.2.7 on 2025-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_initial'),
        ('movies', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(related_name='movie_lists', to='movies.movie'),
        ),
    ]
