# Generated by Django 5.2.7 on 2025-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('description', models.TextField()),
                ('genres', models.ManyToManyField(related_name='movie_genres', to='genres.genre')),
                ('lists', models.ManyToManyField(related_name='movie_lists', to='lists.list')),
            ],
        ),
    ]
